name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: List directory contents (before)
        run: ls -la
      
      - name: Install dependencies
        run: npm ci
      
      - name: List directory contents (after npm ci)
        run: ls -la
      
      - name: Display package.json
        run: cat package.json
      
      - name: Skip build (using static files)
        run: echo "Skipping build step and using static files from simple-app directory"
      
      - name: List simple-app directory
        run: ls -la simple-app
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV_SCAN_SECURITY }}'
          channelId: live
          projectId: dev-scan-security
